src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cms.Web.Mvc.Doctor.Controllers
{
	public class AboutController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Controllers/AuthController.cs
using Cms.Data.Models.Entities;
using Cms.Web.Mvc.Doctor.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Cms.Web.Mvc.Doctor.Controllers
{
    public class AuthController : Controller
    {

        private readonly string _apiUrl = "https://localhost:7078/api/Doctors";
        private readonly HttpClient _httpClient; // Client

        public AuthController(HttpClient httpClient) // Dependency injection ile HttpClient ekleyin
        {
            _httpClient = httpClient;
        }

        [HttpGet("login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost("login")]
        public async Task<IActionResult> Login([FromForm] LoginViewModel login)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // Burada kullanıcıyı doğrulamak için API'yi kullanabilirsiniz
            var response = await _httpClient.GetAsync(_apiUrl);

            if (response.IsSuccessStatusCode)
            {
                List<DoctorEntity> model = await _httpClient.GetFromJsonAsync<List<DoctorEntity>>(_apiUrl);
                var mainModel = model.FirstOrDefault(u => u.Email == login.Email && u.Password == login.Password);

                if (mainModel != null)
                {
                    // Kullanıcı doğrulandı, kimlik bilgilerini oluştur ve oturum aç
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, mainModel.Name),
                        new Claim(ClaimTypes.Surname, mainModel.Surname),
                        // Diğer kimlik bilgilerini burada ekleyebilirsiniz
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

                    var authProperties = new AuthenticationProperties
                    {
                        ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                        IsPersistent = login.RememberMe
                    };

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal, authProperties);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    // Eşleşen doktor bulunamadı, hata mesajı görüntüle
                    ViewBag.Error = "Kullanıcı adı veya şifre hatalı";

                    return View(login);
                }
            }
            else
            {
                // API ile iletişim sırasında bir hata oluştu, hata mesajı görüntüle
                ViewBag.Error = "API ile iletişim sırasında bir hata oluştu.";

                return View(login);
            }

        }

        [HttpGet("logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction(nameof(Login));
        }

        [AllowAnonymous]
        [HttpGet("register")]
        public IActionResult Register()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost("register")]
        public async Task<IActionResult> Register([FromForm] RegisterViewModel register)
        {
            if (!ModelState.IsValid)
            {
                return View(register);
            }

            if (register.Password != register.PasswordVerify)
            {
                ViewBag.Error = "Şifreler uyuşmuyor";

                return View(register);
            }

            var user = new DoctorEntity
            {
                Name       = register.Name,
                Surname    = register.Surname,
                Email      = register.Email,
                Password   = register.Password,
                CategoryId = register.CategoryId,


            };

            var response = await _httpClient.PostAsJsonAsync(_apiUrl, user);

            if (response.IsSuccessStatusCode)
            {
                ViewBag.Message = "Kullanıcı Başarıyla kaydedildi.";
            }

            return View();
        }

    }
}

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cms.Web.Mvc.Doctor.Controllers
{
	public class BlogController : Controller
	{
		public IActionResult Index()
		{
			return this.View();
		}

		public IActionResult Detail()
		{
			return this.View();
		}
	}
}

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Controllers/DoctorController.cs
using Cms.Data.Models.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Cms.Web.Mvc.Doctor.Controllers
{
	public class DoctorController : Controller
	{

		private readonly HttpClient _httpClient;
		private readonly string _apiDoctor = "https://localhost:7078/api/Doctors";

		public DoctorController(HttpClient httpClient)
		{
			_httpClient = httpClient;
		}

		public async Task<ActionResult> Index()
		{
			var model = await _httpClient.GetFromJsonAsync<List<DoctorEntity>>(_apiDoctor);

			return View(model);
		}

		public async Task<ActionResult> Detail(int id)
		{
			// Belirli bir doktorun detaylarını getir.
			var doctor = await _httpClient.GetFromJsonAsync<DoctorEntity>($"{_apiDoctor}/{id}");

			if (doctor == null)
			{
				// Belirli bir doktor bulunamazsa hata sayfasına yönlendirme yapılabilir.
				return NotFound();
			}

			return View(doctor);
		}
	}
}

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Views/Shared/_FooterPartial.cshtml
<footer class="footer section gray-bg">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 mr-auto col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<div class="logo mb-4">
						<img src="images/logo.png" alt="" class="img-fluid">
					</div>
					<p>Tempora dolorem voluptatum nam vero assumenda voluptate, facilis ad eos obcaecati tenetur veritatis eveniet distinctio possimus.</p>

					<ul class="list-inline footer-socials mt-4">
						<li class="list-inline-item">
							<a href="https://www.facebook.com/themefisher"><i class="icofont-facebook"></i></a>
						</li>
						<li class="list-inline-item">
							<a href="https://twitter.com/themefisher"><i class="icofont-twitter"></i></a>
						</li>
						<li class="list-inline-item">
							<a href="https://www.pinterest.com/themefisher/"><i class="icofont-linkedin"></i></a>
						</li>
					</ul>
				</div>
			</div>

			<div class="col-lg-2 col-md-6 col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Department</h4>
					<div class="divider mb-4"></div>

					<ul class="list-unstyled footer-menu lh-35">
						<li><a href="#!">Surgery </a></li>
						<li><a href="#!">Wome's Health</a></li>
						<li><a href="#!">Radiology</a></li>
						<li><a href="#!">Cardioc</a></li>
						<li><a href="#!">Medicine</a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-2 col-md-6 col-sm-6">
				<div class="widget mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Support</h4>
					<div class="divider mb-4"></div>

					<ul class="list-unstyled footer-menu lh-35">
						<li><a href="#!">Terms & Conditions</a></li>
						<li><a href="#!">Privacy Policy</a></li>
						<li><a href="#!">Company Support </a></li>
						<li><a href="#!">FAQuestions</a></li>
						<li><a href="#!">Company Licence</a></li>
					</ul>
				</div>
			</div>

			<div class="col-lg-3 col-md-6 col-sm-6">
				<div class="widget widget-contact mb-5 mb-lg-0">
					<h4 class="text-capitalize mb-3">Get in Touch</h4>
					<div class="divider mb-4"></div>

					<div class="footer-contact-block mb-4">
						<div class="icon d-flex align-items-center">
							<i class="icofont-email mr-3"></i>
							<span class="h6 mb-0">Support Available for 24/7</span>
						</div>
						<h4 class="mt-2"><a href="mailto:support@email.com">Support@email.com</a></h4>
					</div>

					<div class="footer-contact-block">
						<div class="icon d-flex align-items-center">
							<i class="icofont-support mr-3"></i>
							<span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
						</div>
						<h4 class="mt-2"><a href="tel:+23-345-67890">+23-456-6588</a></h4>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-btm py-4 mt-5">
			<div class="row align-items-center justify-content-between">
				<div class="col-lg-6">
					<div class="copyright">
						Copyright &copy; 2021, Designed &amp; Developed by <a href="https://themefisher.com/">Themefisher</a>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="subscribe-form text-lg-right mt-5 mt-lg-0">
						<form action="#" class="subscribe">
							<input type="text" class="form-control" placeholder="Your Email address" required>
							<button type="submit" class="btn btn-main-2 btn-round-full">Subscribe</button>
						</form>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4">
					<a class="backtop scroll-top-to" href="#top">
						<i class="icofont-long-arrow-up"></i>
					</a>
				</div>
			</div>
		</div>
	</div>
</footer>

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Views/Shared/_HeadPartial.cshtml
<head>

    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Novena- Health Care &amp; Medical template</title>

    <!-- Mobile Specific Metas
    ================================================== -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Health Care Medical Html5 Template">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
    <meta name="author" content="Themefisher">
    <meta name="generator" content="Themefisher Novena HTML Template v1.0">

    <!-- theme meta -->
    <meta name="theme-name" content="novena" />

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.png" />

    <!--
    Essential stylesheets
    =====================================-->
    <link rel="stylesheet" href="~/plugins/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/plugins/icofont/icofont.min.css">
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick/slick.css">
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick/slick-theme.css">

    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="~/css/style.css">

</head>

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Views/Shared/_HeaderPartial.cshtml
<nav class="navbar navbar-expand-lg navigation" id="navbar">
	<div class="container">
		<a asp-controller="Home" asp-action="Index" class="navbar-brand">
			<img src="~/images/logo.png" alt="" class="img-fluid">
		</a>

		<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain"
				aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
			<span class="icofont-navigation-menu"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarmain">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item active"><a asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
				<li class="nav-item"><a asp-controller="About" asp-action="Index" class="nav-link">About</a></li>
				<li class="nav-item"><a asp-controller="Service" asp-action="Index" class="nav-link">Services</a></li>

				<li class="nav-item dropdown">
					<a asp-controller="Department" asp-action="Index" class="nav-link dropdown-toggle" id="dropdown02" data-toggle="dropdown"
					   aria-haspopup="true" aria-expanded="false">Department <i class="icofont-thin-down"></i></a>
					<ul class="dropdown-menu" aria-labelledby="dropdown02">
						<li><a asp-controller="Department" asp-action="Index" class="dropdown-item">Departments</a></li>
						<li><a asp-controller="Department" asp-action="Detail" class="dropdown-item">Department Single</a></li>

						<li class="dropdown dropdown-submenu dropright">
							<a class="dropdown-item dropdown-toggle" href="#!" id="dropdown0301" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sub Menu</a>

							<ul class="dropdown-menu" aria-labelledby="dropdown0301">
								<li><a class="dropdown-item" href="index.html">Submenu 01</a></li>
								<li><a class="dropdown-item" href="index.html">Submenu 02</a></li>
							</ul>
						</li>
					</ul>
				</li>

				<li class="nav-item dropdown">
					<a <a asp-controller="Doctor"  class="nav-link dropdown-toggle" id="dropdown03" data-toggle="dropdown"
							   aria-haspopup="true" aria-expanded="false">Doctors <i class="icofont-thin-down"></i></a>
							<ul class="dropdown-menu" aria-labelledby="dropdown03">
								<li><a asp-controller="Doctor" asp-action="Index" class="dropdown-item" >Doctors</a></li>
								<li><a asp-controller="Doctor" asp-action="Detail" class="dropdown-item" >Doctor Single</a></li>
								<li><a asp-controller="Appointment" asp-action="Index" class="dropdown-item" >Appoinment</a></li>

								<li class="dropdown dropdown-submenu dropleft">
									<a class="dropdown-item dropdown-toggle" href="#!" id="dropdown0501" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sub Menu</a>

									<ul class="dropdown-menu" aria-labelledby="dropdown0501">
										<li><a class="dropdown-item" href="index.html">Submenu 01</a></li>
										<li><a class="dropdown-item" href="index.html">Submenu 02</a></li>
									</ul>
								</li>
							</ul>
				</li>

				<li class="nav-item dropdown">
					<a asp-controller="Blog" asp-action="Index" class="nav-link dropdown-toggle" id="dropdown05" data-toggle="dropdown"
					   aria-haspopup="true" aria-expanded="false">Blog <i class="icofont-thin-down"></i></a>
					<ul class="dropdown-menu" aria-labelledby="dropdown05">
						<li><a asp-controller="Blog" asp-action="Index" class="dropdown-item">Blog with Sidebar</a></li>
						<li><a asp-controller="Blog" asp-action="Detail" class="dropdown-item">Blog Single</a></li>
					</ul>
				</li>
				<li class="nav-item"><a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a></li>
			</ul>
		</div>
	</div>
</nav>

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<!--
// WEBSITE: https://themefisher.com
// TWITTER: https://twitter.com/themefisher
// FACEBOOK: https://www.facebook.com/themefisher
// GITHUB: https://github.com/themefisher/
-->

<html lang="en">

<partial name="_HeadPartial" />

<body id="top">

<header>
    <partial name="_TopBarPartial" />
    @* 	<partial name="_HeaderPartial" /> *@

    @await Component.InvokeAsync("Navbar")
      

</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<partial name="_FooterPartial" />
<partial name="_ScriptsPartial" />

</body>
</html>

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Views/Shared/_ScriptsPartial.cshtml
<!--
Essential Scripts
=====================================-->
<script src="~/plugins/bootstrap/bootstrap.min.js"></script>
<script src="~/plugins/slick-carousel/slick/slick.min.js"></script>
<script src="~/plugins/shuffle/shuffle.min.js"></script>

<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA"></script>
<script src="~/plugins/google-map/gmap.js"></script>

<script src="~/js/script.js"></script>

src/DotNetCoreMvcCms/Cms.Web.Mvc.Doctor/Views/Shared/_TopBarPartial.cshtml
@using System.Security.Claims;
@{
    var girisyapti = User.Identity.IsAuthenticated;
}
<div class="header-top-bar">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <ul class="top-bar-info list-inline-item pl-0 mb-0">
                    <li class="list-inline-item"><a href="mailto:support@gmail.com"><i class="icofont-support-faq mr-2"></i>support@novena.com</a></li>
                    <li class="list-inline-item"><i class="icofont-location-pin mr-2"></i>Address Ta-134/A, New York, USA </li>
                </ul>
            </div>
            <div class="col-lg-6">
                <div class="text-lg-right top-right-bar mt-2 mt-lg-0">
                    <a href="tel:+23-345-67890">
                        <span>Call Now : </span>
                        <span class="h4">823-4565-13456</span>
                    </a>
                </div>
            </div>
            <span>
                @{
                    if (girisyapti)
                    {
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                    }
                }
            </span>
        </div>
    </div>
</div>